name: compile-on-tag

on:
  push:
    tags:
      - '*'
      
jobs:
  compile-card:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Latex document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: card.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: card.pdf
          repo-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
